// 【文件说明】esbuild 打包脚本（M4 工单：把 server 打成单文件 CJS bundle 供 Electron 内嵌）
//
// 关键点：
//   - 入口 server/src/embed.ts（导出 startServer），不引 index.ts（CLI 入口保持原样）；
//   - platform=node 让 esbuild 自动 externalize node:sqlite / fs / http 等内置模块；
//   - target=node22 匹配 Electron 37 内置 Node 22.21，async/await / node:sqlite 都覆盖；
//   - format=cjs 匹配 Electron 主进程 CJS 输出，方便 require()；
//   - 产物 dist/server/server.cjs 同时被 dev / prod 用：
//       dev：<projectRoot>/dist/server/server.cjs（被 main.ts 按 __dirname 推算路径加载）
//       prod：electron-builder.yml 的 extraResources 把 dist/server 拷到 resources/server/，
//             主进程按 process.resourcesPath 加载。
//
// 为什么要走 esbuild 而不是直接用 tsx（CLI）：
//   - Electron 主进程是单文件入口 out/main/main.js，所有依赖必须打到 bundle 里；
//   - tsx 是运行时编译器，启动成本 + 与 Electron 主进程 CJS 互操作都有摩擦；
//   - esbuild 单文件 bundle 启动快、零运行时依赖，是 M4 嵌入的标配。

import { build } from "esbuild"
import { mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(here, "..")
const outFile = resolve(projectRoot, "dist", "server", "server.cjs")

// 确保产物目录存在
mkdirSync(dirname(outFile), { recursive: true })

const start = Date.now()
const result = await build({
  entryPoints: [resolve(projectRoot, "server/src/embed.ts")],
  outfile: outFile,
  bundle: true,
  platform: "node",
  target: "node22",
  format: "cjs",
  // platform=node 已经把 node: 内置模块标 external；这里再显式列一遍做兜底
  // （避免 esbuild 版本差异时漏掉 node:sqlite 等较新的内置模块）
  external: [
    "node:sqlite",
    "node:fs",
    "node:fs/promises",
    "node:path",
    "node:http",
    "node:url",
    "node:module",
    "node:os",
    "node:crypto",
    "node:stream",
    "electron",
  ],
  // 不做 tree-shake 太狠：server 路由之间互相 import，副作用依赖保持
  treeShaking: true,
  // 让 require() 在 Electron 主进程里可被 source-map 工具定位到 .ts
  sourcemap: false,
  // banner 注释：标注是 M4 工单产物，方便排查
  banner: {
    js: "// Petibi embedded server bundle (M4 工单：Electron 主进程内嵌)\n// Generated by scripts/build-server.mjs — do not edit by hand.",
  },
  // metafile 用于调试 + 给交付报告产出包大小
  metafile: true,
  logLevel: "info",
  // 抑制已知的空 import.meta.url 警告（内嵌模式已通过 publicDirOverride/postersDirOverride
  // 注入路径；CLI 模式走 tsx 不会遇到此警告）
  logOverride: {
    "empty-import-meta": "silent",
  },
})

const ms = Date.now() - start
const outputs = Object.values(result.metafile?.outputs ?? {})
const bytes = outputs.reduce((acc, o) => acc + (o.bytes ?? 0), 0)
console.log(
  `[build-server] done in ${ms}ms → ${outFile} (${(bytes / 1024).toFixed(1)} KiB)`,
)